global_parameters:
  c: 300000000                      # speed of light
  type_tx_signal: pulse             # supported: chirp, pulsed, continuous wave
  bandwidth: 200000000              # bandwidth of the signal, 200e6 Hz
  P_tx: 30                          # transmitted power in watts

tx_parameters:
  fc: 10000000000                   # carrier freq, 10e9 Hz
  amplitude: 1                      # amplitude of the signal
  initial_phase_offset: 0
  pulse:
    pulse_width: 0.00002            # pulse width, 20 micro-seconds
    n_pulses: 128                   # number of pulses
    prf: 2000                       # pulse repetition frequency
    modulation_type: lfm
  cw:
    modulation_type: fmcw

antenna_parameters:
  n_antenna_elements: 8             # number of antenna elements in the array
  ula_spacing: 0.5                  # spacing between antenna elements
  Gain: 25                          # gain of the antenna
  Losses: 3                         # losses in the system

rx_parameters:
  target_rcs: 1                     # amplitude
  max_unambiguous_range: 1          # meters
  n_samples: 2048                   # number of samples per chirp
  clutter:
    num_clutter_points: 5
    clutter_amplitude: 1

target_parameters:
  point_target:
    - target_id: 0
      range_m: 50.0
      velocity_mps: 10.0
      rcs_dbsm: 0.0
    - target_id: 1
      range_m: 80.0
      velocity_mps: -5.0
      rcs_dbsm: -3.0
  # drones:
  #   - target_id: 2